<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>手写Promise教程</title>
</head>
<body>

    <script type="text/javascript">

        class Promise {
            // executor /ɪg'zekjʊtə/ n.执行者
            constructor(executor) {
                // 初始化 state 为等待态
                this.state = "pending";
                // 成功的值
                this.value = undefined;
                // 失败的原因
                this.reason = undefined;

                // 成功存放的数组
                this.onResolvedCallbacks = [];
                // 失败存放的数组
                this.onRejectedCallbacks = [];


                let resolve = (value) => {
                    if (this.state === "pending") {
                        // resolve 调用后, state 转化为成功态
                        this.state = "fulfilled";
                        // 存储成功的值
                        this.value = value;
                        // 一旦 resolve 执行，调用成功数组的函数
                        // forEach() 对数组中的每一项运行给定函数
                        this.onResolvedCallbacks.forEach( (fn) => { fn();} );
                    }
                };

                let reject = (reason) => {
                    // state 改变， reject 调用就会失败
                    if (this.state === "pending") {
                        // reject 调用后， state 转化为失败态
                        this.state = "rejected";
                        // 存储失败的原因
                        this.reason = reason;
                        // 一旦 reject 执行，调用失败数组的函数
                        this.onRejectedCallbacks.forEach( (fn) => { fn();} )
                    }
                };

                // 如果 executor 执行报错，直接执行 reject
                try {
                    executor(resolve, reject);
                } catch(err) {
                    reject(err);
                }
            }

            then(onFulfilled, onRejected) {

                // onFulfilled 如果不是函数， 就忽略 onFulfilled 直接返回 value
                onFulfilled = typeof onFulfilled === "function" ? onFulfilled : (value) => { return value };
                // onRejected 如果不是函数，就忽略 onRejected 直接扔出错误
                onRejected = typeof onRejected === "function" ? onRejected : (err) => { throw err };

                /** # 2. 解决链式回调: ~~start */
                // 声明返回的 promise2
                let promise2 = new Promise(
                    (resolve, reject) => {
                        // 状态为 fulfilled, 执行 onFulfilled, 传入成功的值
                        if (this.state === "fulfilled") {
                            // 异步
                            setTimeout( () => {
                                try {
                                    let x = onFulfilled(this.value);
                                    // resolvePromise 函数，处理自己 return 的 promise 和默认的 promise2 的关系
                                    resolvePromise(promise2, x, resolve, reject);
                                } catch (e) {
                                    reject(e);
                                }
                            }, 0)
                        }

                        // 状态为 rejected, 执行 onRejected, 传入失败的原因
                        if (this.state === "rejected") {
                            // 异步
                            setTimeout(() => {
                                // 如果报错
                                try {
                                    let x = onRejected(this.reason);
                                    resolvePromise(promise2, x, resolve, reject);
                                } catch (e) {
                                    reject(e);
                                }
                            }, 0)
                        }

                        // 当状态 state 为 pending 时
                        if (this.state === "pending") {
                            // onFulfilled 传入到成功数组
                            if (onFulfilled !== undefined) {
                                this.onResolvedCallbacks.push(
                                    () => {
                                        // 异步
                                        setTimeout(() => {
                                            try {
                                                let x = onFulfilled(this.value);
                                                resolvePromise(promise2, x, resolve, reject);
                                            } catch (e) {
                                                reject(e);
                                            }
                                        }, 0)
                                    }
                                );
                            }

                            // onRejected 传入到失败数组
                            if (onRejected !== undefined) {
                                this.onRejectedCallbacks.push(
                                    () => {
                                        // 异步
                                        setTimeout(() => {
                                            try {
                                                let x = onRejected(this.reason);
                                                resolvePromise(promise2, x, resolve, reject);
                                            } catch (e) {
                                                reject(e);
                                            }
                                        }, 0)
                                    }
                                )
                            }

                        }
                    }
                    );

                // 返回 promise2, 完成链式
                return promise2;
                /** # 2. 解决链式回调: ~~end */
            }

            /** # 5. catch() 方法 */
            catch(fn){
                return this.then(null,fn);
            }
        }

        function resolvePromise(promise2, x, resolve, reject) {
            // 循环引用报错
            if (x === promise2) {
                // reject 报错: 监测到 promise 的链接周期
                return reject(new TypeError("Chaining cycle detected for promise."));
            }
            // 防止多次调用
            let called;
            // x 不是 null 且 x 是对象或者函数
            if (x !== null && (typeof x === "object" || typeof x === "function")) {
                try {
                    // A+ 规定，声明 then = x 的 then 方法
                    let then = x.then;
                    // 如果 then 是函数，就默认是 promise 了
                    if (typeof  then === "function") {
                        // 就让 then 执行第一个参数是 this 后面是成功的回调和失败的回调
                        then.call(
                            x,
                            (y) => {
                                // 成功的和失败的只能调用一个
                                if (called) return;
                                called = true;
                                // resolve 的结果依旧是 promise 那就继续解析
                                resolvePromise(promise2, y, resolve, reject);
                            },
                            (err) => {
                                // 成功和失败的只能调用一个
                                if (called) return;
                                called = true;
                                // 失败了也就失败了
                                reject(err);
                            }
                        )
                    } else {
                        // 直接成功即可
                        resolve(x);
                    }
                } catch(e) {
                    // 也属于失败
                    if (called) return;
                    called = true;
                    // 取 then 出错了那就不要在继续执行了
                    reject(e);
                }
            } else {
                resolve(x);
            }
        }


        /** # 6. resolve() 方法 */
        Promise.resolve = function(val) {
            // 在 Promise.race 中用到，使 Promise 对象: Promise.resolve(1) 和 普通值:3 之间公平竞争。原则
            if () {}
        };

        /** # 7. reject() 方法 */
        Promise.reject = function(val) {
            return new Promise((resolve, reject) => {
                reject(val);
            })
        };

        /** # 8. race() 方法 */
        // 原文章内写的并不对，所以代码只写到这里
        // 20180903-Promise-github\repromise-master\promise.js 的写法

        /** # 9. all() 方法(获取所有的 promise, 都执行 then, 把结果放到数组，一起返回) */
        // 原文章内写的并不对，所以代码只写到这里



        let p = new Promise (
            // function 函数传入到 Promise 对象中就是 executor 函数
            function (resolve, reject) {
               setTimeout(function() {
                   resolve(0);
                   reject(1);
               }, 500)
            },
        );
        p.then(
            (data) => {
                console.log(data);
                return 2;
            }
        ).then(
            (data) => {
                console.log(data);
                return 3;
            }
        );


        // 测试链式2 (这段测试是目前看到别的文章用的最多的)
       /* function task() {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve("task");
                }, 1000)
            })
        }
        task().then((data) => {
            console.log(data);
            return "taskB";
        }).then((data) => {
            console.log(data);
            return "taskC";
        }).then((data) => {
            console.log(data);
            throw new Error();
        }).catch(e => {
            console.log(e);
            return "taskD"; // 此处错误提示输出和原生的 Promise 错误输出不太一样
        }).then((data) => {
            console.log(data);
        })*/



    </script>
</body>
</html>